#!/bin/sh
# postinst script
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)

      sed -i 's|this.selectedAppBox.set_height(0);|//this.selectedAppBox.set_height(0);|g' /usr/share/cinnamon/applets/menu@cinnamon.org/applet.js || true

      RUID=$(who | awk 'FNR == 1 {print $1}')
      RUSER_UID=$(id -u ${RUID})
      
      if [ "$RUID" != "" ] ; then
        if [ ! -f /home/${RUID}/.config/autostart/plank.desktop ] ; then
          cp /etc/skel/.config/autostart/plank.desktop /home/${RUID}/.config/autostart/
        fi
        sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" hamonikr-theme-start jin
      fi

      gtk-update-icon-cache || true

    ;;
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;
    triggered)


    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0